config/routes.rb
Rails.application.routes.draw do
  devise_for :functionaries
  devise_for :admins
  root to: 'home#index'
  resources :shipping_companies, only: [:index, :new, :create, :show, :edit, :update] do
    resources :vehicles, only: [:index, :show, :new, :create]
    resources :price_settings, only: [:index, :new, :create]  
    resources :deadlines, only: [:index, :new, :create] 
    resources :product_models, only: [:index, :new, :create, :show]
    post'active', on: :member
    post'inactive', on: :member
  end
  resources :service_orders, only: [:index, :new, :create, :show, :edit, :update] do
    resources :delivery_routes, only: [:new, :create] 
    get 'search', on: :collection
    post'accept', on: :member
    post'recused', on: :member   
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :shipping_company
  validates :name, :weight, :width, :height, :depth, :sku, presence: true
  validates :sku, uniqueness: true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController 
  def index
    @shipping_company = ShippingCompany.find(params[:shipping_company_id])
    @product_models = @shipping_company.product_models
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end

  def new
    @shipping_company = ShippingCompany.find(params[:shipping_company_id])
    @product_model = ProductModel.new
  end

  def create
    @shipping_company =  ShippingCompany.find(params[:shipping_company_id])
    @product_model = ProductModel.new(product_model_params)
    @product_model.shipping_company = @shipping_company
    if  @product_model.save() 
      redirect_to shipping_company_product_models_path(@shipping_company), notice: "Produto cadastrado com sucesso."
    else
      flash.now[:notice] = 'Não foi possível cadastrar o produto.'
      render 'new'
    end
  end

  private

  def product_model_params
    params.require(:product_model).permit(:name, :weight, :width, :height, :depth, :sku)
  end
end

app/views/product_models/index.html.erb
<section>
<% if admin_signed_in? %>
  <div>
    <%= link_to('Cadastrar Produto', new_shipping_company_product_model_path)%>
  </div>
 <% end %>
  <h2>Modelos de Produtos</h2>
  <% if @product_models.any? %>
    <% @product_models.each do |product| %>
      <table>
      <tr>
        <th><%= ProductModel.human_attribute_name(:name)%>: </th>
        <td><%= product.name %></td>
      </tr>
      <tr>
        <th><%= ProductModel.human_attribute_name(:sku)%>: </th>
        <td><%= link_to product.sku, shipping_company_product_model_path(@shipping_company.id, product.id) %> </td>
      </tr>
      </table> 
    <% end %>
  <% else %>
    <p>Não existem modelos de produtos cadastrados.</p>
  <% end %>
  <div>
  <%= link_to 'Voltar', shipping_company_path(@shipping_company.id) %> 
  </div>
</section>

app/views/product_models/new.html.erb
<h2>Novo Produto</h2>

<% if (@product_model.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @product_model.errors.full_messages.each do |msg| %>
    <li><%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: [@shipping_company, @product_model]) do |f| %>
  <div>
    <%= f.label :name  %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight, step: 0.01 %>
  </div>

  <div>
    <%= f.label :width %>
    <%= f.number_field :width, step: 0.01 %>
  </div>
  
  <div>
    <%= f.label :height %>
    <%= f.number_field :height, step: 0.01 %>
  </div>

  <div>
    <%= f.label :depth %>
    <%= f.number_field :depth, step: 0.01 %>
  </div>

  <div>
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>

  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/product_models/show.html.erb
<h2><%= ProductModel.model_name.human %></h2>
<table border="1">
  <tr>
    <th><%= ProductModel.human_attribute_name(:name)%>:</th>
    <td><%= @product_model.name %></td>
  </tr>
  <tr>
    <th><%= ProductModel.human_attribute_name(:weight)%>:</th>
    <td><%= @product_model.weight %></td>
  </tr>
  <tr>
    <th><%= ProductModel.human_attribute_name(:width)%>:</th>
    <td><%= @product_model.width %></td>
  </tr>
  <tr>
    <th><%= ProductModel.human_attribute_name(:height)%>:</th>
    <td><%= @product_model.height %></td>
  </tr>
  <tr>
    <th><%= ProductModel.human_attribute_name(:depth)%>:</th>
    <td><%= @product_model.depth %></td>
  </tr>
  <tr>
    <th><%= ProductModel.human_attribute_name(:sku)%>:</th>
    <td><%= @product_model.sku %> </td>
  </tr>
</table>
<div>
  <%= link_to 'Voltar', shipping_company_product_models_path %> 
</div>