config/routes.rb
Rails.application.routes.draw do
  devise_for :functionaries
  devise_for :admins
  root to: 'home#index'
  resources :shipping_companies, only: [:index, :new, :create, :show, :edit, :update] do
    resources :vehicles, only: [:index, :show, :new, :create]
    resources :price_settings, only: [:index, :new, :create]  
    resources :deadlines, only: [:index, :new, :create] 
    resources :product_models, only: [:index, :new, :create, :show]
    post'active', on: :member
    post'inactive', on: :member
  end
  resources :service_orders, only: [:index, :new, :create, :show, :edit, :update] do
    resources :delivery_routes, only: [:new, :create] 
    get 'search', on: :collection
    post'accept', on: :member
    post'recused', on: :member   
  end
end

app/models/shipping_company.rb
class ShippingCompany < ApplicationRecord
    before_validation :save_email_domain
    enum status: { active: 0, inactive: 5 }
    
    has_many :vehicles
    has_many :functionaries
    has_many :price_settings
    has_many :product_models
    has_many :service_orders
     

    validates :corporate_name, :fantasy_name, :email, :cnpj , :address, :city, :state, :cep, presence: true
    validates :cnpj, uniqueness: true
    validates :cnpj, length: { is: 14 }

    def save_email_domain
      self.email_domain = self.email.split("@")[1]
    end
end

app/controllers/shipping_companies_controller.rb
class ShippingCompaniesController < ApplicationController 
  before_action :authenticate_admin!, only: [:index, :new, :create, :edit, :update]

  def index
    @shipping_companies = ShippingCompany.all
  end

  def new
    @shipping_company = ShippingCompany.new
  end

  def show
    @shipping_company = ShippingCompany.find(params[:id])
  end

  def create
    @shipping_company = ShippingCompany.new(shipping_company_params)
    if @shipping_company.save()
      redirect_to shipping_companies_path, notice: "Transportadora cadastrada com sucesso."
    else
      flash.now[:notice] = "Transportadora não cadastrada."
      render'new'
    end
  end

  def edit 
    @shipping_company = ShippingCompany.find(params[:id])
  end

  def update
    @shipping_company = ShippingCompany.find(params[:id])     
    if @shipping_company.update(shipping_company_params)
      redirect_to shipping_companies_path(@shipping_company.id), notice: 'Transportadora atualizada com sucesso.'
    else
      flash.now[:notice] = 'Não foi possível atualizar a transportadora.'
      render'edit'
    end
  end

  def active
    @shipping_company = ShippingCompany.find(params[:id])
    @shipping_company.active!
    redirect_to shipping_company_path(@shipping_company.id), notice: 'Transportadora ativada com sucesso!'
  end

  def inactive
    @shipping_company = ShippingCompany.find(params[:id])
    @shipping_company.inactive!
    redirect_to shipping_company_path(@shipping_company.id), notice: 'Transportadora desativada com sucesso!'
  end

  private


  def shipping_company_params
    params.require(:shipping_company).permit( :corporate_name, :fantasy_name, :email, 
                                              :cnpj , :address, :city, :state, :cep)
  end
end

app/views/shipping_companies/_form.html.erb
<%= form_with(model: @shipping_company) do |f| %>
  <div>
    <%= f.label :corporate_name%>
    <%= f.text_field :corporate_name %>
  </div>

  <div>
    <%= f.label :fantasy_name %>
    <%= f.text_field :fantasy_name%>
  </div>

  <div>
    <%= f.label :cnpj%>
    <%= f.text_field :cnpj %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div>
    <%= f.label :cep %>
    <%= f.number_field :cep %>
  </div>
  
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/shipping_companies/edit.html.erb
<h2>Editar Transportadora</h2>

<%= render 'form'%>

app/views/shipping_companies/index.html.erb
<section>
<% if admin_signed_in? %>
  <div>
    <%= link_to('Cadastrar Transportadora', new_shipping_company_path)%>
  </div>
  <h2>Transportadoras</h2>
  <% if @shipping_companies.any? %>
    <% @shipping_companies.each do |s| %>
      <table>
        <tr>
          <td><%= ShippingCompany.model_name.human %>: </td>
          <th><%= link_to(s.fantasy_name, shipping_company_path(s.id))%></th>
        </tr>
        <tr>
          <td><%= ShippingCompany.human_attribute_name(:cnpj)%>:</td>
          <th><%= s.cnpj %> </th>
        </tr>
      </table>
    <% end %>
  <% else %>
    <p>Não existem transportadoras cadastradas.</p>
  <% end %>
<% end %>
</section>

app/views/shipping_companies/new.html.erb
<h2>Nova Transportadora</h2>

<% if (@shipping_company.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @shipping_company.errors.full_messages.each do |msg| %>
    <li><%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= render 'form'%>

app/views/shipping_companies/show.html.erb
<h2>Detalhes da Transportadora: </h2>
  <table>
  <tr>
    <th><%= ShippingCompany.human_attribute_name(:fantasy_name)%>:</th>
    <td><%= @shipping_company.fantasy_name %></td>
  </tr>
  <tr>
    <th><%= ShippingCompany.human_attribute_name(:corporate_name)%>:</th>
    <td><%= @shipping_company.corporate_name %></td>
  </tr>
  <tr>
    <th><%= ShippingCompany.human_attribute_name(:cnpj)%>:</th>
    <td><%= @shipping_company.cnpj %></td>
  </tr>
  <tr>
    <th><%= ShippingCompany.human_attribute_name(:email)%>:</th>
    <td><%= @shipping_company.email %></td>
  </tr>
  <tr>
    <th><%= ShippingCompany.human_attribute_name(:address)%>:</th>
    <td><%= @shipping_company.address %></td>
  </tr>
  <tr>
    <th><%= ShippingCompany.human_attribute_name(:city)%>:</th>
    <td><%= @shipping_company.city %></td>
  </tr>
  <tr>
    <th><%= ShippingCompany.human_attribute_name(:state)%>:</th>
    <td><%= @shipping_company.state %></td>
  </tr>
  <tr>
    <th><%= ShippingCompany.human_attribute_name(:cep)%>:</th>
    <td><%= @shipping_company.cep %></td>
  </tr>
  <tr>
    <th><%= ShippingCompany.human_attribute_name(:status)%>:</th>
    <td><%= t(@shipping_company.status) %></td>
  </tr>
  </table>

<% if admin_signed_in? %>
  <div>
    <%= link_to('Produtos', shipping_company_product_models_path(@shipping_company.id))%> |
    <%= link_to('Voltar', shipping_companies_path) %> | 
    <%= link_to('Editar', edit_shipping_company_path(@shipping_company.id))%> |
    <%= button_to('Ativar', active_shipping_company_path(@shipping_company.id)) %>
    <%= button_to('Desativar', inactive_shipping_company_path(@shipping_company.id)) %>
  </div>
<% end %>