config/routes.rb
Rails.application.routes.draw do
  devise_for :functionaries
  devise_for :admins
  root to: 'home#index'
  resources :shipping_companies, only: [:index, :new, :create, :show, :edit, :update] do
    resources :vehicles, only: [:index, :show, :new, :create]
    resources :price_settings, only: [:index, :new, :create]  
    resources :deadlines, only: [:index, :new, :create] 
    resources :product_models, only: [:index, :new, :create, :show]
    post'active', on: :member
    post'inactive', on: :member
  end
  resources :service_orders, only: [:index, :new, :create, :show, :edit, :update] do
    resources :delivery_routes, only: [:new, :create] 
    get 'search', on: :collection
    post'accept', on: :member
    post'recused', on: :member   
  end
end

app/models/service_order.rb
class ServiceOrder < ApplicationRecord
  belongs_to :shipping_company
  belongs_to :vehicle
  belongs_to :product_model
  has_many :delivery_route
    
  enum status: { pending: 0, accept: 1, recused:2, delivered: 5, canceled: 9 }

  validates :code, :estimated_delivery_date, presence: true 
  validate :estimated_delivery_date_is_future

  before_validation :generate_code
    
  private

  def generate_code
    self.code = SecureRandom.alphanumeric(15).upcase
  end

  def estimated_delivery_date_is_future
    if self.estimated_delivery_date.present? && self.estimated_delivery_date <= Date.today
      self.errors.add(:estimated_delivery_date, "deve ser posterior.")
    end
  end
end

app/controllers/service_orders_controller.rb
class ServiceOrdersController < ApplicationController 
  #before_action :authenticate_admin!
  def index
    @service_orders = ServiceOrder.all
  end

  def show
    @service_order = ServiceOrder.find(params[:id])
  end

  def new
    @service_order = ServiceOrder.new
    @shipping_companies = ShippingCompany.all    
    @vehicles = Vehicle.all
    @product_models = ProductModel.all  
  end

  def create    
    service_order_params = params.require(:service_order).permit(:shipping_company_id, :vehicle_id, :product_model_id, :full_address, 
                                                        :customer_address, :customer_name, :estimated_delivery_date, :status)
    @service_order = ServiceOrder.new(service_order_params)
    if @service_order.save
      redirect_to @service_order, notice: 'Pedido registrado com sucesso.'
    else
      @shipping_companies = ShippingCompany.all
      @vehicles = Vehicle.all
      @product_models = ProductModel.all
      flash.now[:notice] = 'Não foi possível registrar o pedido.'
    render 'new'
    end
  end

  def search
    @code = params["query"]
    @service_orders = ServiceOrder.where("code LIKE ?", "%#{@code}%")
  end

  def accept
    @service_order = ServiceOrder.find(params[:id])
    @service_order.accept!
    redirect_to service_order_path(@service_order.id), notice: 'Pedido aceito com sucesso!'
  end

  def recused
    @service_order = ServiceOrder.find(params[:id])
    @service_order.recused!
    redirect_to service_order_path(@service_order.id), notice: 'Pedido recusado com sucesso!'
  end

end

app/views/service_orders/index.html.erb
<section>
  <h2>Ordens de Serviço</h2>
  <% if @service_orders.any? %>
    <% @service_orders.each do |order| %>
      <table>
        <tr>
        <th><%= link_to order.code, order %></th> 
        <td><%= t(order.status) %></td>
        </tr>
      </table> 
    <% end %>
  <% else %>
    <p>Não existem ordens de serviço cadastradas.</p>
  <% end %>
</section>

app/views/service_orders/new.html.erb
<h2>Registrar Pedido</h2>

<% if (@service_order.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @service_order.errors.full_messages.each do |msg| %>
    <li><%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @service_order) do |f|%>
  <div>
    <%= f.label :shipping_company_id%>
    <%= f.collection_select :shipping_company_id, @shipping_companies, :id, :corporate_name %>
  </div>

  <div>
    <%= f.label :vehicle_id %>
    <%= f.collection_select :vehicle_id, @vehicles, :id, :model %>
  </div>

  <div>
    <%= f.label :product_model_id %>
    <%= f.collection_select :product_model_id, @product_models, :id, :sku %>
  </div>

  <div>
    <%= f.label :full_address %>
    <%= f.text_area :full_address %>
  </div>

  <div>
    <%= f.label :customer_address %>
    <%= f.text_area :customer_address %>
  </div>

  <div>
    <%= f.label :customer_name %>
    <%= f.text_field :customer_name %>
  </div>

  <div>
    <%= f.label :estimated_delivery_date %>
    <%= f.date_field :estimated_delivery_date %>
  </div>
  
  <div>
    <%= f.submit 'Gravar'%>
  </div>
<% end %>

app/views/service_orders/search.html.erb
<h1>Resultados da Busca por: <%= @code %></h1>

<% if @service_order.present? %>
  <p>1 pedido encontrado</p>
  <dl>
    <dt><%= ServiceOrder.human_attribute_name(:code)%>:</dt>
    <dd><%= @service_order.code %></dd>
    <dt><%= ServiceOrder.human_attribute_name(:shipping_company_id)%>:</dt>
    <dd><%= @service_order.shipping_company.corporate_name %></dd>
    <dt><%= ServiceOrder.human_attribute_name(:vehicle_id)%>:</dt>
    <dd><%= @service_order.vehicle.model %></dd>
    <dt><%= ServiceOrder.human_attribute_name(:product_model_id)%>:</dt>
    <dd><%= @service_order.product_model.sku %></dd>
  </dl>
  
<% end %>

<p><%= @service_orders.count %> <%= ServiceOrder.model_name.human(count: @service_orders.count).downcase %> <%= I18n.translate(:found, count: @service_orders.count)%></p>
<% @service_orders.each do |order| %>
  <dl>
    <dt><%= ServiceOrder.human_attribute_name(:code)%>:</dt>
    <dd><%= link_to order.code, order %> Consulte RASTREAMENTO </dd> 
    <dt><%= ServiceOrder.human_attribute_name(:shipping_company_id)%>:</dt>
    <dd><%= order.shipping_company.corporate_name %></dd>
    <dt><%= ServiceOrder.human_attribute_name(:vehicle_id)%>:</dt>
    <dd><%= order.vehicle.model %></dd>
    <dt><%= ServiceOrder.human_attribute_name(:product_model_id)%>:</dt>
    <dd><%= order.product_model.sku %></dd>
    <dt><%= ServiceOrder.human_attribute_name(:status)%>:</dt> 
    <dd><%= t(order.status) %></dd>
  </dl>
<% end %>

app/views/service_orders/show.html.erb
<h1>Detalhes do Pedido:</h1>

<table>
<h2><%= ServiceOrder.model_name.human %>: <%= @service_order.code %></h2>
<tr>
  <th><%= ServiceOrder.human_attribute_name(:shipping_company_id)%>:</th> 
  <td><%= @service_order.shipping_company.corporate_name %></td>
</tr>
<tr>
  <th><%= ServiceOrder.human_attribute_name(:vehicle_id)%>:</th> 
  <td><%= @service_order.vehicle.model %></td>
</tr>
<tr>
  <th><%= ServiceOrder.human_attribute_name(:product_model_id)%>:</th>
  <td><%= @service_order.product_model.sku %></td>
</tr>
<tr>
  <th><%= ServiceOrder.human_attribute_name(:full_address)%>:</th>
  <td><%= (@service_order.full_address) %></td>
</tr>
<tr>
  <th><%= ServiceOrder.human_attribute_name(:customer_address)%>:</th> 
  <td><%= (@service_order.customer_address) %></td>
</tr>
<tr>
  <th><%= ServiceOrder.human_attribute_name(:customer_name)%>:</th> 
  <td><%= (@service_order.customer_name) %></td>
</tr>
<tr>
  <th><%= ServiceOrder.human_attribute_name(:estimated_delivery_date)%>:</th> 
  <td><%= I18n.localize(@service_order.estimated_delivery_date) %></td>
</tr>
<tr>
  <th><%= ServiceOrder.human_attribute_name(:status)%>:</th>
  <td><%= t(@service_order.status) %></td>
</tr>
</table>

<br>
<h3>RASTREAMENTO</h3>
<p>Objeto em trânsito - por favor aguarde</p>

<div>
<% if functionary_signed_in? %>

  <% if @service_order.pending? %>
    <%= button_to "Aceitar", accept_service_order_path(@service_order.id) %>
    <%= button_to "Recusar", recused_service_order_path(@service_order.id) %>
  <% end %>
  <%= link_to "Voltar", service_orders_path %>
  
  <%= link_to "Atualizar rota", new_service_order_delivery_route_path(service_order_id: @service_order.id) %>
<% end %>
</div>

<div>
  <% @service_order.delivery_route.each do |f|%>
    <table>
    <tr>
      <th><%= DeliveryRoute.human_attribute_name(:current_address)%>:</th>
      <td><%= f.current_address %></td>
    </tr>
    <tr>
      <th><%= DeliveryRoute.human_attribute_name(:exit_address)%>:</th>
      <td><%= f.exit_address %></td>
    </tr>
    <tr>
      <th><%= DeliveryRoute.human_attribute_name(:current_date)%>:</th>
      <td><%= f.current_date %></td>
    </tr> 
    </table>
    <br>
  <% end %>
<div>