config/routes.rb
Rails.application.routes.draw do
  devise_for :functionaries
  devise_for :admins
  root to: 'home#index'
  resources :shipping_companies, only: [:index, :new, :create, :show, :edit, :update] do
    resources :vehicles, only: [:index, :show, :new, :create]
    resources :price_settings, only: [:index, :new, :create]  
    resources :deadlines, only: [:index, :new, :create] 
    resources :product_models, only: [:index, :new, :create, :show]
    post'active', on: :member
    post'inactive', on: :member
  end
  resources :service_orders, only: [:index, :new, :create, :show, :edit, :update] do
    resources :delivery_routes, only: [:new, :create] 
    get 'search', on: :collection
    post'accept', on: :member
    post'recused', on: :member   
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> DeliverySystem </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" %>
  </head>
  <body>
    <header>
     <%= link_to root_path do %>
        <h1> Sistema de Entregas </h1>
      <% end %>
    
        <nav> 
        <% if !admin_signed_in? && !functionary_signed_in?%>
         |<%= link_to "Área do Funcionário", new_functionary_session_path %> |
          <%= link_to "Área Admin", new_admin_session_path %> |
        <% end %>

        <% if admin_signed_in? %>
          Olá <%= current_admin.email %>
        | <%= link_to 'Transportadoras', shipping_companies_path %> |
          <%= link_to 'Registrar Pedido', new_service_order_path %> |
          <%= link_to 'Meus Pedidos', service_orders_path %> |
          <%= button_to "Sair", destroy_admin_session_path, method: :delete %>
        <% end %>

        <% if functionary_signed_in? %>
          Olá <%= current_functionary.email %>
        | <%= link_to 'Minha Transportadora', shipping_company_path(current_functionary.shipping_company) %> | 
          <%= link_to 'Pedidos', service_orders_path %> |
          <%= link_to 'Veículos', shipping_company_vehicles_path(current_functionary.shipping_company) %> | 
          <%= link_to 'Tabela de Preços', shipping_company_price_settings_path(current_functionary.shipping_company) %> |
          <%= link_to 'Prazos de Entrega', shipping_company_deadlines_path(current_functionary.shipping_company) %> |
          
          <%= button_to "Sair", destroy_functionary_session_path, method: :delete %>
        <% end %>
        </nav>

        <div>
          <%= form_with(url: search_service_orders_path, method: :get) do |f|%>
            <%= f.label :query,'Buscar Pedido' %>
            <%= f.text_field :query %>
            <%= f.submit 'Buscar' %>
          <% end %>
        </div>
    </header>

    <main>
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <%= yield %>
    </main>
  </body>
</html>